#! /bin/sh
# Generated by cmake

rm -f testInversion.cout
"/Users/jaenam/Desktop/Work/EIC/runall/2.4.1.3/Matrix/test/testInversion" > testInversion.cout
diff -q -b testInversion.cout "/Users/jaenam/Desktop/Work/EIC/runall/2.4.1.3/CLHEP/Matrix/test/testInversion.output"
