#! /bin/sh
# Generated by cmake


"/Users/jaenam/Desktop/Work/EIC/runall/2.4.1.3/Random/test/testRandDists" < "/Users/jaenam/Desktop/Work/EIC/runall/2.4.1.3/CLHEP/Random/test/testRandDists.input" \
  | sed 's/e-00\([0-9]\)/e-0\1/g' \
  | sed 's/e+00\([0-9]\)/e+0\1/g' \
  | diff -q -b - "/Users/jaenam/Desktop/Work/EIC/runall/2.4.1.3/CLHEP/Random/test/testRandDists.output" > /dev/null
