#! /bin/sh
# Generated by cmake


./testBasicVector3D < "/Users/jaenam/Desktop/Work/EIC/runall/2.4.1.3/CLHEP/Geometry/test/testBasicVector3D.input" \
  | diff -q -b - "/Users/jaenam/Desktop/Work/EIC/runall/2.4.1.3/CLHEP/Geometry/test/testBasicVector3D.output" > /dev/null
