#! /bin/sh
# Generated by cmake


./testThreeVector < "/Users/jaenam/Desktop/Work/EIC/runall/2.4.1.3/CLHEP/Vector/test/testThreeVector.input" \
  | diff -q -b - "/Users/jaenam/Desktop/Work/EIC/runall/2.4.1.3/CLHEP/Vector/test/testThreeVector.output" > /dev/null
