#! /bin/sh
# Generated by cmake


./testLorentzVector < "/Users/jaenam/Desktop/Work/EIC/runall/2.4.1.3/CLHEP/Vector/test/testLorentzVector.input" \
  | diff -q -b - "/Users/jaenam/Desktop/Work/EIC/runall/2.4.1.3/CLHEP/Vector/test/testLorentzVector.output" > /dev/null
