#! /bin/sh
# Generated by cmake


./testVectorDists < "/Users/jaenam/Desktop/Work/EIC/runall/2.4.1.3/CLHEP/RandomObjects/test/testVectorDists.input" \
  | diff -q -b - "/Users/jaenam/Desktop/Work/EIC/runall/2.4.1.3/CLHEP/RandomObjects/test/testVectorDists.output" > /dev/null
